[package]
name = "hello_rust"
version = "0.1.0"
edition = "2024"
default-run = "hello_rust"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.41", features = ["macros", "rt-multi-thread"] }
